### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by asad-awadia** [DrAshBooth/JavaLOB#2]
```

fun main() {
  val ob = OrderBook(1.0)
  println(ob.processOrder(Order((System.currentTimeMillis() / 1000).toInt(), true, 100, 1, "offer", 90.0), true))
  println(ob.processOrder(Order((System.currentTimeMillis() / 1000).toInt(), true, 100, 2, "bid", 91.0), true))
}

```

```
Exception in thread "main" java.lang.NullPointerException
	at lob.OrderReport.toString(OrderReport.java:46)
	at java.base/java.lang.String.valueOf(String.java:2932)
	at java.base/java.io.PrintStream.println(PrintStream.java:977)
	at exthash.MainKt.main(main.kt:32)
	at exthash.MainKt.main(main.kt)
```

**Comment by asad-awadia** [comment]
@DrAshBooth
